export const grades = [
  "Intern",
  "Junior",
  "Junior+",
  "Middle",
  "Middle+",
  "Senior",
  "Senior+",
  "Team Lead",
  "Lead Developer",
  "Lead Engineer",
  "Staff Engineer",
  "Principal Engineer",
  "Architect",
  "Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "CTO",
];
