export const positions = [
  "Developer",
  "Frontend",
  "Backend",
  "Full-stack",
  "QA Engineer",
  "Designer",
  "Project Manager",
  "DevOps Engineer",
  "System Administrator",
  "Data Scientist",
  "Product Manager",
  "Business Analyst",
  "UX Designer",
];
