import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CompanyScore | Отзыв',
  description: 'Generated by create next app',
};

export default async function CommentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
