module.exports = {
  extends: '@istanbuljs/nyc-config-typescript',
  all: true,
  'check-coverage': true,
  branches: 80,
  lines: 80,
  functions: 80,
  statements: 80,
  exclude: [
    'coverage/**',
    'packages/*/test{,s}/**',
    '**/*.d.ts',
    'cypress/**',
    'test{,s}/**',
    'test{,-*}.{js,cjs,mjs,ts,tsx,jsx}',
    '**/*{.,-}test.{js,cjs,mjs,ts,tsx,jsx}',
    '**/*{.,-}spec.{js,cjs,mjs,ts,tsx,jsx}',
    '**/__tests__/**',
    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
    '**/.{eslint,mocha,prettier}rc.{js,cjs,ts}',
    '**/{main,renderer,preload}.{js,cjs,mjs,ts,jsx,tsx}',
    '**/electron-builder.{js,cjs,mjs,ts}',
    '**/next-env.d.ts',
    '**/next.config.{js,ts}',
    '**/postcss.config.{js,ts}',
    '**/tailwind.config.{js,ts}',
    '**/jest.config.{js,ts}',
    '**/.mocharc.{js,ts}',
    '**/.nycrc.{js,ts}',
    '**/middleware.{js,ts}',
    '**/env.example',
    '**/.env*',
    '**/Dockerfile*',
    '**/.dockerignore',
    '**/.gitignore',
    '**/README.md',
    '**/package*.json',
    '**/tsconfig*.json',
    '**/.eslintrc*',
    '**/.prettierrc*',
    '**/public/**',
    '**/node_modules/**',
    '**/.next/**',
    '**/out/**',
    '**/dist/**',
    '**/build/**',
    '**/.husky/**',
    '**/.github/**',
    '**/components/**',
    '**/widgets/**',
    '**/features/**',
    '**/shared/**',
    '**/constants/**',
    '**/api/**',
    '**/store/**',
    '**/lib/**',
    '**/app/**/*.tsx',
    '**/app/**/*.jsx',
    '**/app/**/layout.tsx',
    '**/app/**/page.tsx',
    '**/app/**/loading.tsx',
    '**/app/**/error.tsx',
    '**/app/**/not-found.tsx',
    '**/app/**/globals.css',
    '**/app/**/favicon.ico',
    '**/app/**/providers.tsx',
    '**/app/**/tanstack.tsx',
    '**/app/**/modals/**',
    '**/app/**/components/**',
    '**/app/**/api/**',
    '**/app/**/test/**',
    '**/app/**/login/**',
    '**/app/**/profile/**',
    '**/app/**/users/**',
    '**/app/**/companies/**',
    '**/app/**/comments/**',
    '**/app/**/about/**',
    '**/app/**/blog/**',
    '**/app/**/analytic/**',
    '**/app/**/access/**',
  ],
  reporter: ['text', 'text-summary', 'html', 'lcov', 'json'],
  'report-dir': 'coverage',
  'temp-dir': '.nyc_output',
  'source-map': true,
  instrument: true,
  'cache-dir': '.nyc_cache',
};
