import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CompanyScore | Аналитика',
  description: 'Generated by create next app',
};

export default async function AnalyticLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
