import { Metadata } from 'next';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'CompanyScore | Отзывы',
  description: 'Generated by create next app',
};

export default async function CommentsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const hasAccess = cookieStore.get('hasAccess')?.value;

  if (hasAccess != '777888999') {
    redirect('/access');
  }

  return <>{children}</>;
}
