import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CompanyScore | Блог',
  description: 'Generated by create next app',
};

export default async function BlogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
