import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import { Header, HeaderMobile, Footer } from '@/widgets';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'CompanyScore | Главная',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const refreshToken = cookieStore.get('refreshToken')?.value;

  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased flex flex-col min-h-screen font-sans`}
      >
        {/* <ThemeProvider> */}
        <Header />
        <HeaderMobile />

        <main className="flex-1 h-full">{children}</main>
        {refreshToken && <Footer />}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
