import { Metadata } from 'next';
import { Auth } from '@/features';
import { useState } from 'react';

import { Hero, Features, Steps, Reviews, Blog, Call } from './components';

export const metadata: Metadata = {
  title: 'CompanyScore | Главная',
  description: 'Generated by create next app',
};

export default async function HomePage() {
  const [visible, setVisible] = useState(false);

  return (
    <section className="flex flex-col items-stretch justify-center">
      <Hero />
      <Features />
      <Steps />
      <Reviews />
      <Blog />
      <Call />

      <Auth type="login" visible={visible} setVisible={setVisible} />
    </section>
  );
}
