import { Metadata } from "next";

// import { Button } from "@nextui-org/button";
// import { useState } from "react";

export const metadata: Metadata = {
  title: "CompanyScore | Home",
  description: "Generated by create next app",
};

export default function HomePage() {
  // const [count, setCount] = useState();
  return (
    <section className="flex flex-col items-stretch justify-center gap-8 py-8 md:py-10 m-auto">
      <div>Наши Донатеры!</div>
      <div>Новые Компании!</div>
      <div>Новые Пользователи!</div>
    </section>
  );
}
