import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CompanyScore | Профиль',
  description: 'Generated by create next app',
};

export default async function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
