import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CompanyScore | Login',
  description: 'Generated by create next app',
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex-1 container mx-auto h-full px-4">{children}</main>
  );
}
