import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CompanyScore | Логин',
  description: 'Generated by create next app',
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
