export const positions = [
  { label: "Developer", value: "developer" },
  { label: "Frontend", value: "frontend" },
  { label: "Backend", value: "backend" },
  { label: "Full-stack", value: "fullstack" },
  { label: "QA Engineer", value: "qa" },
  { label: "Designer", value: "designer" },
  { label: "Project Manager", value: "project-manager" },
  { label: "DevOps Engineer", value: "devops" },
  { label: "System Administrator", value: "system-administrator" },
  { label: "Data Scientist", value: "data-scientist" },
  { label: "Product Manager", value: "product-manager" },
  { label: "Business Analyst", value: "business-analyst" },
  { label: "UX Designer", value: "ux" },
];
