// import { Geist, Geist_Mono } from "next/font/google";
// import "@/app/global.css"; // Подключаем общие стили
// import Header from "@/components/general/header";
// import Footer from "@/components/general/footer";
// import ThemeProvider from "@/shared/theme-provider";

import { Metadata } from "next";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "CompanyScore | Компании",
  description: "Generated by create next app",
};

export default function CompaniesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex-1 container mx-auto h-full px-4">{children}</main>
  );
}
